# Generated by Django 4.2.5 on 2023-09-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=200)),
                ('name_last', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=200)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_city', models.CharField(max_length=200)),
                ('address_state', models.CharField(max_length=2)),
                ('address_country_code', models.CharField(max_length=2)),
                ('address_postal_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('document_ssn', models.CharField(max_length=9)),
            ],
        ),
    ]
